//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filtration.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Filtration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_01 {
            get {
                return ResourceManager.GetStream("AlertSound_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_02 {
            get {
                return ResourceManager.GetStream("AlertSound_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_03 {
            get {
                return ResourceManager.GetStream("AlertSound_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_04 {
            get {
                return ResourceManager.GetStream("AlertSound_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_05 {
            get {
                return ResourceManager.GetStream("AlertSound_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_06 {
            get {
                return ResourceManager.GetStream("AlertSound_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_07 {
            get {
                return ResourceManager.GetStream("AlertSound_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_08 {
            get {
                return ResourceManager.GetStream("AlertSound_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_09 {
            get {
                return ResourceManager.GetStream("AlertSound_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_10 {
            get {
                return ResourceManager.GetStream("AlertSound_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_11 {
            get {
                return ResourceManager.GetStream("AlertSound_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_12 {
            get {
                return ResourceManager.GetStream("AlertSound_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_13 {
            get {
                return ResourceManager.GetStream("AlertSound_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_14 {
            get {
                return ResourceManager.GetStream("AlertSound_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_15 {
            get {
                return ResourceManager.GetStream("AlertSound_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_16 {
            get {
                return ResourceManager.GetStream("AlertSound_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Area Damage
        ///Armour
        ///Attack Damage
        ///Attack Damage while Dual Wielding
        ///Attack Damage while holding a Shield
        ///Aura Effect
        ///Axe and Sword Damage
        ///Bow Damage
        ///Brand Damage
        ///Chance to Block Attack Damage
        ///Chance to Block Spell Damage
        ///Channelling Skill Damage
        ///Chaos Damage
        ///Chaos Damage over Time
        ///Chaos Resistance
        ///Cold Damage
        ///Cold Damage over Time
        ///Cold Resistance
        ///Critical Chance
        ///Curse Effect
        ///Dagger and Claw Damage
        ///Damage over Time
        ///Damage while you have a Herald
        ///Damage with Two Handed Weapons
        ///Effect of [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string EnchantmentPassiveNode {
            get {
                return ResourceManager.GetString("EnchantmentPassiveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Arc Tower Chain
        ///Arc Tower Damage
        ///Arc Tower Range
        ///Arc Tower Repeat
        ///Arc Tower Sap Chance
        ///Chilling Tower Chill Effect
        ///Chilling Tower Damage
        ///Chilling Tower Duration
        ///Chilling Tower Range
        ///Chilling Tower Special
        ///Empowering Tower Cast Speed
        ///Empowering Tower Damage
        ///Empowering Tower Effect
        ///Empowering Tower Range
        ///Empowering Tower Special
        ///Fireball Tower Additional Projectile
        ///Fireball Tower Cast Speed
        ///Fireball Tower Damage
        ///Fireball Tower Range
        ///Fireball Tower Special
        ///Flamethrower Tower Cast Speed
        ///Fla [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Enchantments {
            get {
                return ResourceManager.GetString("Enchantments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] Fontin_SmallCaps {
            get {
                object obj = ResourceManager.GetObject("Fontin_SmallCaps", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap groundtile {
            get {
                object obj = ResourceManager.GetObject("groundtile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Shaper
        ///Elder
        ///Crusader
        ///Hunter
        ///Redeemer
        ///Warlord
        ///None 的當地語系化字串。
        /// </summary>
        internal static string Influences {
            get {
                return ResourceManager.GetString("Influences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A Chilling Wind
        ///A Dab of Ink
        ///A Dusty Memory
        ///A Familiar Call
        ///A Fate Worse Than Death
        ///A Modest Request
        ///A Mother&apos;s Parting Gift
        ///A Note in the Wind
        ///A Sea of Blue
        ///A Stone Perfected
        ///Abandoned Wealth
        ///Aberrant Fossil
        ///Abrasive Catalyst
        ///Absolution
        ///Abyss Scarab
        ///Abyss Scarab of Edifice
        ///Abyss Scarab of Emptiness
        ///Abyss Scarab of Multitudes
        ///Abyssal Axe
        ///Abyssal Delirium Orb
        ///Abyssal Incubator
        ///Abyssal Sceptre
        ///Accelerating Catalyst
        ///Acclimatisation
        ///Accumulator Wand
        ///Added Chaos Damage Support
        ///Added Col [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ItemBaseTypes {
            get {
                return ResourceManager.GetString("ItemBaseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abyss Jewels
        ///Active Skill Gems
        ///Amulets
        ///Atlas Upgrade Items
        ///Belts
        ///Blueprints
        ///Body Armours
        ///Boots
        ///Bows
        ///Breachstones
        ///Charms
        ///Claws
        ///Contracts
        ///Corpses
        ///Currency
        ///Daggers
        ///Divination Cards
        ///Fishing Rods
        ///Flasks
        ///Gems
        ///Gloves
        ///Gold
        ///Heist Brooches
        ///Heist Cloaks
        ///Heist Gear
        ///Heist Targets
        ///Heist Tools
        ///Helmets
        ///Hybrid Flasks
        ///Incubators
        ///Incursion Items
        ///Jewels
        ///Labyrinth Items
        ///Labyrinth Trinkets
        ///Life Flasks
        ///Logbooks
        ///Mana Flasks
        ///Map Fragments
        ///Maps
        ///Memories
        ///Misc Map Items
        ///One Hand
        ///One Hand Axes        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ItemClasses {
            get {
                return ResourceManager.GetString("ItemClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abating
        ///Abbot&apos;s
        ///Abecedarian&apos;s
        ///Abundant
        ///Acolyte&apos;s
        ///Acrobat&apos;s
        ///Acute
        ///Adaptable
        ///Adept&apos;s
        ///Adroit
        ///Affecting
        ///Aged
        ///Agile
        ///Alarmed
        ///Alchemist&apos;s
        ///Allocated
        ///Alluring
        ///Alpine
        ///Ample
        ///Analyst&apos;s
        ///Anarchist&apos;s
        ///Annealed
        ///Annest&apos;s
        ///Anointed
        ///Apparition&apos;s
        ///Apprentice&apos;s
        ///Aqua
        ///Archmage&apos;s
        ///Arcing
        ///Armadillo&apos;s
        ///Artificer&apos;s
        ///Athlete&apos;s
        ///Azure
        ///Barbed
        ///Baron&apos;s
        ///Baroness&apos;s
        ///Beatified
        ///Beetle&apos;s
        ///Behemoth&apos;s
        ///Beryl
        ///Bishop&apos;s
        ///Biting
        ///Bitter
        ///Blacksmith&apos;s
        ///Blasting
        ///Blazing
        ///Blessed
        ///Blistering
        ///Bloodthirsty
        ///Blue
        ///Blurred
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ItemMods {
            get {
                return ResourceManager.GetString("ItemMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Alchemy {
            get {
                return ResourceManager.GetStream("SH22Alchemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Blessed {
            get {
                return ResourceManager.GetStream("SH22Blessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Chaos {
            get {
                return ResourceManager.GetStream("SH22Chaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Divine {
            get {
                return ResourceManager.GetStream("SH22Divine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Exalted {
            get {
                return ResourceManager.GetStream("SH22Exalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Fusing {
            get {
                return ResourceManager.GetStream("SH22Fusing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22General {
            get {
                return ResourceManager.GetStream("SH22General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Mirror {
            get {
                return ResourceManager.GetStream("SH22Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Regal {
            get {
                return ResourceManager.GetStream("SH22Regal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Vaal {
            get {
                return ResourceManager.GetStream("SH22Vaal", resourceCulture);
            }
        }
    }
}
